### ISSUE TITLE
horizontal bar chart (barh) is upside-down

### ISSUE THREAD

**Issue by suntong** [plotly/plotly.github.io#110]
As reported at [stackoverflow](http://stackoverflow.com/questions/34076177/matplotlib-horizontal-bar-chart-barh-is-upside-down), when the vertical bar charts are converted to horizontal bar chart (from `bar` to `barh`), everything is upside-down. I.e., for a grouped bar chart, not only the order of the grouped bar is wrong, the order of the each group is wrong as well.

As the simplest demo, I changed `kind='bar'`, to `kind='barh'`, from this graph https://plot.ly/pandas/bar-charts/#pandas-grouped-bar-chart and the result looks like this: https://plot.ly/7/~xpt/.

 People from the Microsoft Excel world are complaining about this in Excel all over the places. The Microsoft Excel has a fix for it, can Ploty have a fix for it please? Our company is trying to streamline the old heavy manual process to generate reports in Excel, and Plotly is a best solution for us for the moment. This is the only road-block for us to convert to Plotly. Thanks.

**Comment by suntong** [comment]
OK, from the [stackoverflow Q&A](http://stackoverflow.com/questions/34076177/matplotlib-horizontal-bar-chart-barh-is-upside-down), the solution is simply, reversing the y axis.

For matplotlib, it is 

    py.gca().invert_yaxis()

For Pandas, it is

    ax.invert_yaxis()

What's Ploty's syntax? Thanks.

**Comment by cldougl** [comment]
Hi @suntong if you need to reverse the axis you can check out this parameter: https://plot.ly/python/reference/#layout-yaxis-autorange
If you have additional questions please post in our help forum: http://community.plot.ly/ (this repo handles docs for our online GUI)
