### ISSUE TITLE
Plotly offiline in R did not show any graph in either Rstudio Viewer or Browser

### ISSUE THREAD

**Issue by MengyingLi** [plotly/plotly.github.io#111]
Hi 

I was running the example codes on your website but there was no graph showing up anywhere. No error occurred either.

I am using R 3.2.1, RStudio Version 0.98.1103 , Windows 10.

Thanks.

**Comment by chriddyp** [comment]
Hey @MengyingLi - can you reopen this issue in the [Plotly R library](https://github.com/ropensci/plotly)? 
You may want to try to upgrade your RStudio version, older versions aren't compatible with html widgets.
Thanks!
