### ISSUE TITLE
Fix headings in sharing tutorial

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#122]
http://help.plot.ly/how-sharing-works-in-plotly/ -- the headings aren't rendering correctly

**Comment by tarzzz** [comment]
Works on local, probably broken due to jekyll version update .. :/

![image](https://cloud.githubusercontent.com/assets/1546532/12907907/03ba795a-cf17-11e5-8307-328c714108b5.png)

**Comment by tarzzz** [comment]
headings have been fixed. Please have a quick review, and close this one.. :dancers:

**Comment by cldougl** [comment]
Thank you!! (thanks for getting the lists at the bottom too :+1: )
