### ISSUE TITLE
Not able to set axis and graph Title using Jupiter notebook (python)  in plotly offline

### ISSUE THREAD

**Issue by dvigneshwer** [plotly/plotly.github.io#133]
Using plotly offine in my ipython notebook, the graph is coming properly.
But its axis title and graph is not coming.

Ex Code:
import plotly
from plotly.graph_objs import *
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot

init_notebook_mode()
trace1 = go.Scatter(
    x=[0, 1, 2, 3, 4, 5, 6, 7, 8],
    y=[0, 1, 2, 3, 4, 5, 6, 7, 8],
    name='Name of Trace 1'
)
trace2 = go.Scatter(
    x=[0, 1, 2, 3, 4, 5, 6, 7, 8],
    y=[1, 0, 3, 2, 5, 4, 7, 6, 8],
    name='Name of Trace 2'
)
data = [trace1, trace2]
layout = go.Layout(
    title='Plot Title',
    xaxis=dict(
        title='x Axis',
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    ),
    yaxis=dict(
        title='y Axis',
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    )
)
iplot(data, layout)
The graph is coming out properly but title and graph title is not coming.

**Comment by dvigneshwer** [comment]
How to add graph title ,axis names and legend in ipython notebook if using plotly?

**Comment by cldougl** [comment]
Hi @dvigneshwer  , looks like you imported `from plotly.graph_objs import *` but then used go.Function syntax. If you're still having a problem can you post in our question forum: http://community.plot.ly/
(this repo handles docs for our online GUI)
