### ISSUE TITLE
Box and Lines on the same Chart (with same x coordinates)

### ISSUE THREAD

**Issue by delanoe** [plotly/plotly.github.io#145]
It seems we can only plot boxes or lines on different charts, not on the same one (using same x coordinate for instance) ? I would like to use boxes as custom error indicators for my lines. Is it possible ? Thanks for your reply.

**Comment by chriddyp** [comment]
it will be possible in the upcoming release of plotly 2. if you have any further questions, try the forum at community.plot.ly
