### ISSUE TITLE
make a bar graph missing images

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.github.io#16]
@chriddyp @NicoleGrondin @mariahhamel @aneda 

(Where and who do I contact when there are content/docs bugs?)

https://plot.ly/online-graphing/tutorials/make-a-bar-graph/ has missing screen shots images

![image](https://cloud.githubusercontent.com/assets/1176674/7667772/35defe8e-fbe5-11e4-821f-b7ec14959158.png)

**Comment by mariahhamel** [comment]
@bpostlethwaite This tutorial has already been updated on help.plot.ly: http://help.plot.ly/how-to-make-a-bar-chart-online/

We're almost ready to finish the migration, and then all tutorials will be hosted there. I think there are 4 tutorials with issues on WP. Hopefully we will be ready to switch to help.plot.ly this week.
