### ISSUE TITLE
Zoom Feature not Working Properly

### ISSUE THREAD

**Issue by ellecj** [plotly/plotly.github.io#175]
The Plotly loading image doesn't disappear on the first image on the Choropleth Excel tutorial [here](http://help.plot.ly/excel/choropleth-maps) There's something wrong with the zoom feature. In both Chrome and Safari.

**Comment by cldougl** [comment]
fixed https://github.com/plotly/plotly.github.io/commit/7dc565a8893625f5f2c787aeb7db85cd42f9451d
