### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.github.io#18]
hey @mariahhamel - tweaks from a few months ago

- [x] change all "how to make a [...]" urls to just "make a [...]"
![image](https://cloud.githubusercontent.com/assets/1280389/6586204/cc7afaac-c745-11e4-9539-2e9d7ff225bf.png)
![image](https://cloud.githubusercontent.com/assets/1280389/6586218/e4e25c20-c745-11e4-8b11-b18db0ae2651.png)

- [x] change excel tutorials to be e.g. "excel/heatmap" instead of "how to make a heatmap in excel"
![image](https://cloud.githubusercontent.com/assets/1280389/6585406/b926c5ea-c73f-11e4-8beb-9985aa9cd9b3.png)

- [x] change "create" to "make" in fits url

- [x] change "how to" in box-plot tutorial to "make a box plot"
![image](https://cloud.githubusercontent.com/assets/1280389/6586113/e39d9a9c-c744-11e4-843e-3ad10a432c6b.png)
 and change "box-plot" to "what is a box plot" 
![image](https://cloud.githubusercontent.com/assets/1280389/6586102/d5163ccc-c744-11e4-906f-14322cae5bdb.png)

- [x] change all "boxplot" copy to "box plot" 
![image](https://cloud.githubusercontent.com/assets/1280389/6586159/5e3b67ca-c745-11e4-974e-64056d650abb.png)

**Comment by mariahhamel** [comment]
+1 thanks, @chriddyp

**Comment by mariahhamel** [comment]
updated

**Comment by mariahhamel** [comment]
reopening so we can have this on record for other contributors

**Comment by chriddyp** [comment]
maybe move to contributor's guide?

On Mon, May 25, 2015 at 2:26 PM, Mariah Hamel <notifications@github.com>
wrote:

> Reopened #18 <https://github.com/plotly/plotly.github.io/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/plotly.github.io/issues/18#event-313188335>.
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team
