### ISSUE TITLE
Logging in using FB broken

### ISSUE THREAD

**Issue by thomasvangurp** [plotly/plotly.github.io#182]
When trying to log in to plot.ly with my connected FB account I am asked to choose a username. Subsequently I cannot get in. The issue is here:
(function() {
    'use strict';
    // Add CSRF token to the header of all AJAX calls
    // From: https://docs.djangoproject.com/en/1.4/ref/contrib/csrf/
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        crossDomain: false, // obviates need for sameOrigin test
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                xhr.setRequestHeader('X-CSRFToken', $.cookie(window.PLOTLYENV.CSRF_COOKIE_NAME));
            }
        }
    });
})();

> `ajax_setup.5320990d0c77.js:13 Uncaught TypeError: Cannot read property 'CSRF_COOKIE_NAME' of undefined`

ajax_setup.5320990d0c77.js:13 Uncaught TypeError: Cannot read property 'CSRF_COOKIE_NAME' of undefined

**Comment by cldougl** [comment]
Thanks for reporting. We're working on a solution. In the meantime you can email community.support@plot.ly if you'd like to set up an alternative log in method.
