### ISSUE TITLE
Incorrect layout applied to Citation tutorial page

### ISSUE THREAD

**Issue by ellecj** [plotly/plotly.github.io#185]
[This](http://help.plot.ly/citations/) citation tutorial looks off. The copy to clipboard aspect of the code block isn't getting applied correctly?

![screen shot 2016-07-22 at 4 21 59 pm](https://cloud.githubusercontent.com/assets/8120592/17070279/fc41da9a-5028-11e6-8d84-57e14dd2fdec.png)
![screen shot 2016-07-22 at 4 22 13 pm](https://cloud.githubusercontent.com/assets/8120592/17070280/fe15ebea-5028-11e6-83bc-0c6e78e9709d.png)
![screen shot 2016-07-22 at 4 22 24 pm](https://cloud.githubusercontent.com/assets/8120592/17070281/ffa44ca4-5028-11e6-8b46-d348cb1fe675.png)

**Comment by cldougl** [comment]
fixed http://help.plot.ly/citations/
