### ISSUE TITLE
Add more options to export tutorial

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#187]
We've gotten some questions on intercom about exporting data as a csv and about exporting the plot w/ the interactivity. The following updates to the exporting tutorial should help out w/ those Qs:

- [ ] Currently the 'Export Your Data' section shows how to export the plot, so maybe that should be titled 'Export Your Plot as a Static Image'
- [ ] Add that people can export the HTML: 'Export Your Plot as an HTML File'
- [ ] Add Export data section that shows how to export csv of data: _new_ 'Export Your Data' section

**Comment by ellecj** [comment]
All done!
