### ISSUE TITLE
Add actioncall-urls for Plotly2 tutorials

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#188]
@ellecj Here's an example: https://github.com/plotly/plotly.github.io/commit/e7e5d60f906005f48de63204f99deb1d0235a124

Adding the `actioncall-url` parameter will let users open the plot in the alpha workspace when they select the 'Open Data in Plotly' button on the left hand side of the tutorials.

I've added it for the scatter tutorial (example) and heatmap tutorial.

**Comment by ellecj** [comment]
All done!
