### ISSUE TITLE
add updating/editing section to data tutorial

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#210]
We can add a section here http://help.plot.ly/add-data-to-the-plotly-grid/ that mentions when grids are updated the chart automatically updates 🎉🎉🎉
(it would be cool to show this point w/ a gif)

**Comment by cldougl** [comment]
annnnnd, relatedly, we should change the tutorial title here http://help.plot.ly/update-a-graphs-data/ to include *in Plotly 1.0*

We shouldn't change the url since we don't have anything to replace it with atm but perhaps when the section is added to  http://help.plot.ly/add-data-to-the-plotly-grid/ you can add a sentence to the original tutorial with a link to the new updating in plotly 2 section

**Comment by ellecj** [comment]
All done!
