### ISSUE TITLE
How to get to shareplot (to view the code) 

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#212]
We get asked pretty often how to view the code of the plots. We should create a tutorial for http://help.plot.ly/tutorials/#fundamentals showing how users can get to the shareplot view and specifically to the code tab (ie: https://plot.ly/~chelsea_lyn/11816/#code)
- [ ] from plot.ly/organize
- [ ] from plot.ly/feed
- [ ] from plot.ly/alpha/workspace

**Comment by ellecj** [comment]
All done!
