### ISSUE TITLE
Basic Dashboard Doc!

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#215]
Getting started with: https://plot.ly/dashboard/create/

New dashboards have a bunch of great new features and still have the ease of drag and drop orientation
-[ ] ability to save to your organize! Easy to find and share
-[ ] editable!!

**Comment by ellecj** [comment]
Good timing. I'm only really starting to get into dashboards.

**Comment by ellecj** [comment]
All done.
