### ISSUE TITLE
possible to template in the links on index.html with the tutorials?

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.github.io#24]
e.g. loop through our posts and add these blocks accordingly? https://github.com/plotly/plotly.github.io/blob/master/index.html#L88-L94 

I'm worried changing a link on a post and forgetting to update the link on the splash!

@NicoleGrondin totally up to you to judge whether this will be a huge pain to template in or not

cc @mariahhamel

**Comment by NicoleGrondin** [comment]
Hi @chriddyp  & @mariahhamel ,
I've added a variable to the header section of the posts we want to show on the front page.
---
popularity: frontpage
---

Any changes will now be automatically updated.
