### ISSUE TITLE
add embed grid section to embed tutorial

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#250]
Since some users were confused/asking about this, we should add a section to: http://help.plot.ly/embed-graphs-in-websites/

Add embed grid section to mention grids can be embedded (like plots) in iframes.
example: (http://codepen.io/plotly/pen/ZpJgvO)

Note grids are saved as private by default so they'll have to make the file public or secret.

**Comment by ellecj** [comment]
All done!
