### ISSUE TITLE
Redo Earlier Plotly 2 Charts to Make them Look Really Nice 

### ISSUE THREAD

**Issue by ellecj** [plotly/plotly.github.io#263]
- [x] Stacked Bar Chart
- [x] Grouped Bar Chart
- [x] Line Chart
- [ ] Scatter Chart
- [ ] Time Series

**Comment by cldougl** [comment]
@ellecj I'd probably
- [ ] dull the trace colors in the [logo tutorial](http://help.plot.ly/logos/) slightly (to set a good styling example :) )
