### ISSUE TITLE
update links to the workspace

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.github.io#277]
- Update all `/alpha/workspace` links to `/create/`
- Update all `/plot` links to `/create/`

We have several new links that should be used for specific chart types:
- [x] Whenever we're linking a user to the workspace to make a bar chart, we should now link to [https://plot.ly/create/bar-chart/](https://plot.ly/create/bar-chart/) instead of just [https://plot.ly/create](https://plot.ly/create)
- [x] Similarly with scatter charts. Link to [https://plot.ly/create/scatter-chart/](https://plot.ly/create/scatter-chart/)
- [x] And pie charts: [https://plot.ly/create/pie-chart/](https://plot.ly/create/pie-chart/)
- [x] And line graphs: [https://plot.ly/create/line-graph/](https://plot.ly/create/line-graph/)
- [x] And infographics: [https://plot.ly/create/infographic/](https://plot.ly/create/infographic/)
- [x] And box plots: [https://plot.ly/create/box-plot/](https://plot.ly/create/box-plot/)
- [x] And histogram: [https://plot.ly/create/histogram/](https://plot.ly/create/histogram/)
- [x] And lines of best fit: [https://plot.ly/create/line-of-best-fit/](https://plot.ly/create/line-of-best-fit/)

These links should be used wherever possible across the documentation and help pages.

cc @ellecj @cldougl

**Comment by ellecj** [comment]
CUTE. 

I'll add this on my list. Thanks!
