### ISSUE TITLE
Cannot plot heatmap into 3D surface in plotly

### ISSUE THREAD

**Issue by laurenfoster** [plotly/plotly.github.io#279]
Hi Github Plotly,

I've read many of your online tutorials, the most directly helpful being this one: 
https://www.r-bloggers.com/3d-plots-with-ggplot2-and-plotly/

I realize that it's old, so I've looked up the new commands in various documentations online. My issue is that the instructions to turn a heatmap into a 3D plot don't seem to work. Even when I follow the examples exactly for the first plot, except changing py$ggplotly(p) to plotly_POST(p), all the options to turn the heatmap plot into a 3D plot are greyed out. The same is true seemingly no matter what format I put the data in for my data (which is a simple 27 point plot of discrete data on x and y and continuous data on z):

Data
![screen shot 2016-11-22 at 4 16 20 pm](https://cloud.githubusercontent.com/assets/23667518/20545900/12ab6998-b0cf-11e6-90f1-1492c309aa54.png)
This shows each model run, but I have a number in each of the categories.

A simpler example would be to plot:
x<-c(a,b,c)
y<-c(h,i,j)
z<-c(1,0.2,3,2,1,0.5,4,2,1.5)
so that each point in z corresponds to a discrete category in x and y.

Any help using Rstudio, ggplot2, and plotly to create an editable 3D surface from this type of data would be helpful.

Thank you,
Lauren

**Comment by cldougl** [comment]
Hi @laurenfoster  !!
This git repo is dedicated to documentation for Plotly's online GUI.
Looks like the issue you're running into is related to our R api. For support questions, we recommend you post in our community forum: https://community.plot.ly/ with the R api tag.
Additionally, if you'd like to report a bug you can do so in our R api repo: https://github.com/ropensci/plotly/ (please note, issues in that repo are reserved for bug reports, as previously mentioned, support questions should be directed to the community forum).
