### ISSUE TITLE
ES tutorial has screenshot from SQL tutorial

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.github.io#322]
Looks like the wrong image was dropped in here:

![image](https://cloud.githubusercontent.com/assets/1865834/26550744/1fb2761a-444d-11e7-8372-69486ddec743.png)

https://help.plot.ly/database-connectors/elasticsearch/

**Comment by cldougl** [comment]
I see, I think this image may have been chosen to illustrate that if you have multiple connections you might have to use the dropdown to get to the connection/database that you need for this session (ie if we connect to our sql db first then the es on a second session, the original sql db will appear 1st and you use the dropdown to select the es).

**Comment by bcdunbar** [comment]
This was covered a while ago when we updated the docs during the Falcon release.
