### ISSUE TITLE
favicon missing from https://help.plot.ly/tutorials/

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#347]
favicon missing from https://help.plot.ly/tutorials/

**Comment by cldougl** [comment]
![screen shot 2018-11-12 at 4 11 00 pm](https://user-images.githubusercontent.com/2789078/48375345-a5bde000-e695-11e8-9f3e-d6a9b3773c5a.png)

**Comment by jdamiba** [comment]
@cldougl I think this issue has been resolved. OK to close this issue?

![screen shot 2019-01-29 at 11 42 25 am](https://user-images.githubusercontent.com/1557650/51924408-fb637800-23ba-11e9-8a09-d8be940bcdf0.png)

**Comment by cldougl** [comment]
@jdamiba awesome- yep!
