### ISSUE TITLE
need to update make a histogram tutorial

### ISSUE THREAD

**Issue by mariahhamel** [plotly/plotly.github.io#35]
just noticed some mixed html and markdown (i think)

![screen shot 2015-05-28 at 5 51 57 pm](https://cloud.githubusercontent.com/assets/5942601/7872008/564d577a-0562-11e5-8f2b-a17686f8fa8a.png)

**Comment by NicoleGrondin** [comment]
@mariahhamel  I thought the raw html was to illustrate the appropriate coding? Not sure though...

**Comment by mariahhamel** [comment]
I bet you're right @NicoleGrondin . I'll move it to the left column. I think that'll be more readable. 

Thanks!
