### ISSUE TITLE
redirect https://help.plot.ly/dashboards.ly/

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#357]
https://help.plot.ly/dashboards.ly/ needs to redirect to https://plot.ly/dashboards-and-reports/

**Comment by cldougl** [comment]
may have to redirect from : https://github.com/plotly/dashboards.ly/blob/gh-pages-new-design-2016/index.html

**Comment by cldougl** [comment]
@bcdunbar could you try making a pr to the gh-pages-new-design-2016 branch (https://github.com/plotly/dashboards.ly/blob/gh-pages-new-design-2016/index.html) to redirect this (I think we've tried to deal w/ this issue before :/ )

**Comment by bcdunbar** [comment]
@cldougl sorry missed the notification for this one yesterday. Yeah, I think we tackled this once before - hopefully the PR resolves it.

**Comment by cldougl** [comment]
Thanks for the help w/ this @bcdunbar !!!
