### ISSUE TITLE
edit Dashboards and Spectacle Section

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#376]
Move 'Dashboards & Spectacle Presentations' ([https://help.plot.ly/tutorials/#dashboard](https://help.plot.ly/tutorials/#dashboard)) section to the bottom of the page and rename to 'Dashboards'

**Comment by jdamiba** [comment]
addressed by https://github.com/plotly/plotly.github.io/pull/382

**Comment by jdamiba** [comment]
This is actually addressed by https://github.com/plotly/plotly.github.io/pull/383
