### ISSUE TITLE
update collab doc

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#387]
update https://help.plot.ly/collaborate-in-plotly/ based on changes detailed in
https://github.com/plotly/streambed/issues/11101

**Comment by nicolaskruchten** [comment]
The big PR https://github.com/plotly/streambed/pull/11584 is about to land, so this issue will shortly be applicable to prod. To sum up the changes: the UI is now in tight sync with the backend. If the backend lets you save it, you can. That means if you're a collaborator on a plot but not its grid, you can save changes to the plot and not the grid, and so on.
