### ISSUE TITLE
Rename Plotly Cloud/Plotly Enterprise

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.github.io#399]
* Plotly Cloud -> Chart Studio Cloud
* Plot.ly Cloud -> Chart Studio Cloud
* Plotly On-Premise(s) -> Chart Studio Enterprise
* Plotly Enterprise -> Chart Studio Enterprise

**Comment by nicolaskruchten** [comment]
Also note that the main "Web app" link off of help.plot.ly should be renamed Chart Studio (that's the web app) and that the nomenclature in https://help.plot.ly/tutorials/ should be standardized to Chart Studio as well.

**Comment by cldougl** [comment]
@jdamiba is this resolved or do you need any help w/ it?

**Comment by jdamiba** [comment]
I think this has been done everywhere.

**Comment by cldougl** [comment]
🎉 great!! I'll close now but feel free to reopen if you notice anything that still needs to be updated.
