### ISSUE TITLE
help.plot.ly wrap up

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.github.io#4]
help.plot.ly is looking really great.
Let me know if I can help in brainstorming on any css, JavaScript, or HTML stuff.
Organizing a few action items here to wrap this up!
(cc @mariahhamel ! )

- [x] Take out drop shadow on image links. Plotly's look in general is very flat.

- [x] Change "Load more" text in button to "View all tutorials". Button should link to "help.plot.ly/tutorials"
![screen shot 2015-04-29 at 6 30 35 pm](https://cloud.githubusercontent.com/assets/1865834/7402733/ef1298a8-ee9c-11e4-8c4f-b23bfd714202.png)

- [x] help.plot.ly/tutorials should be sectioned with same categories as here https://plot.ly/online-graphing in the same order ("Basic charts", "Statistical charts", etc...). :
![screen shot 2015-04-29 at 5 50 56 pm](https://cloud.githubusercontent.com/assets/1865834/7402745/13073d90-ee9d-11e4-9eb4-6802285851a7.png)

- [x] "Basic charts", "Statistical charts", etc... at "help.plot.ly/tutorials" should be anchor links

- [x] Show only first 12 tutorial links in "PLOTLY TUTORIALS" section. These 12 have been our most popular tutorials according to Google Analytics, so let's show them:

/how-to-create-a-line-of-best-fits/
/box-plot/
/histogram/
/how-to-make-a-graph-with-error-bars-online/
/how-to-make-a-line-graph-and-scatter-plot-online/
/how-to-make-a-histogram-online/
/how-to-make-a-heatmap-online/
/how-to-embed-plotly-graphs-in-websites/
/how-to-make-a-graph-with-multiple-axes-online/
/how-to-make-a-bubble-chart-online/
/how-to-make-a-box-plot-online/
/how-to-make-a-bar-chart-online/

- [x] Take out the "Explore" section. That's my bad - should have been clearer about that in the beginning. help.plot.ly/tutorials Will do what "Explore" is doing now in listing all of the tutorials in a sectioned way (see above).

- [ ] Template-in share buttons at top of tutorials pages, like:
https://plot.ly/how-to-make-a-box-plot-online/

- [x] Make API thumb links images smaller:
![screen shot 2015-04-29 at 6 14 18 pm](https://cloud.githubusercontent.com/assets/1865834/7403102/6c089990-eea0-11e4-900f-cdf75610ad79.png)

- [x] Hover info on API thumb link images:
![screen shot 2015-04-29 at 6 22 29 pm](https://cloud.githubusercontent.com/assets/1865834/7403106/7e2fde3a-eea0-11e4-80bd-044051dd8a48.png)

- [x] MATLAB copy: 
" Plotly's MATLAB API client. Create graphs and manage your Plotly account with MATLAB. Convert MATLAB figures to Plotly graphs drawn in D3.js"

- [x] R copy:
 " Plotly's R / RStudio API client. Create graphs and manage your Plotly account with R. Convert ggplot2 figures to Plotly graphs drawn in D3.js"

- [x] Add logo in front of Plotly in header:
![screen shot 2015-04-29 at 7 12 58 pm](https://cloud.githubusercontent.com/assets/1865834/7403347/bbce69d0-eea2-11e4-984f-88269e29b9e3.png)

- [x] Add "connect" logos / links in footer. Make background of this section white:
![screen shot 2015-04-29 at 7 14 56 pm](https://cloud.githubusercontent.com/assets/1865834/7403366/fa4c9baa-eea2-11e4-8a93-01aafc3633a7.png)

- [x] Bring in line spacing slightly on footer items, increase bottom margin:
![screen shot 2015-04-29 at 7 17 35 pm](https://cloud.githubusercontent.com/assets/1865834/7403409/652f3798-eea3-11e4-8caf-72394b31f01e.png)

- [x] Tutorial subheader H2 ---> H3:
![screen shot 2015-04-29 at 7 17 08 pm](https://cloud.githubusercontent.com/assets/1865834/7403412/791d4998-eea3-11e4-8663-3d2b13b65dec.png)

- [ ] @chriddyp can you check meta descriptions, etc - make sure everything's the way you want it for SEO

- [x] Make sure URL links are same as old documentation. Ie,
https://plot.ly/how-to-make-a-box-plot-online/
Will now go to:
help.plot.ly/how-to-make-a-box-plot-online/
These old links are here:
https://github.com/plotly/streambed/blob/master/shelly/learn/urls/web_app_tutorials/urls.py

- [x] Port over Excel tutorials from:
https://plot.ly/create-charts-in-excel-with-plotly/
These are the same as the non-Excel tutorials - they just have an Excel spreadsheet download of the data as their first step. They're basically just to game search - Many of the Excel tutorials rank surprisingly higher than non-Excel tutorials.

- [x] At help.plot.ly/tutorials, a section for "Excel tutorials" at the bottom for these guys ^^^
![screen shot 2015-04-30 at 10 03 07 am](https://cloud.githubusercontent.com/assets/1865834/7414197/0b21cf96-ef1f-11e4-8568-8836bda7bce2.png)

**Comment by troiska** [comment]
Awesome work Nicole! 

Here are some of my comments: 

![13073d90-ee9d-11e4-9eb4-6802285851a7-2](https://cloud.githubusercontent.com/assets/810684/7415461/0ba2fe88-ef27-11e4-9a3f-ac98e533387c.png)

- [ ] Larger spacing between sections and titles
- [ ] Make the thumbnails bigger and the spacing between them wider
- [ ] Make the tutorial titles smaller, so that there is more padding / wider margins around them.

The idea is to expand the layout, use more space so that the page can "breathe" and not all elements are condensed in the centre.

**Comment by NicoleGrondin** [comment]
Hi Jack. Quick question...
RE: use of old URLS
If the plot.ly/online-graphing page used a different URL, Should I still use the ones from the list (https://github.com/plotly/streambed/blob/master/shelly/learn/urls/web_app_tutorials/urls.py)?

e.g.
https://plot.ly/date-format-and-time-series/
https://plot.ly/online-graphing/tutorials/dates-time-series-and-timestamp-formatting-in-plotly/

Thanks!

**Comment by jackparmer** [comment]
Right, use the old URL pathnames that are *not* from /online-graphing.
So use,
help.plot.ly/date-format-and-time-series/
Instead of 
help.plot.ly/dates-time-series-and-timestamp-formatting-in-plotly/

help.plot.ly's looking great!

**Comment by jackparmer** [comment]
@NicoleGrondin You're cruising through this! Let me know if I can help with any css brainstorming. You may already be working on these, but here are a few more minor things that caught my eye tonight:

- [ ] size and spacing of tutorial thumbs on at help.plot.ly and help.plot.ly/tutorials/ is different. I like the smaller size of the thumbs at help.plot.ly, they're a bit less overwhelming. The size of the thumbs between these 2 pages should be the same.

- [ ] At help.plot.ly/tutorials/, fluid layout sometimes breaks:
![image](https://cloud.githubusercontent.com/assets/1865834/7507644/d47a2aca-f440-11e4-92ec-daad6b3b5b55.png)

- [ ] At help.plot.ly/tutorials/, #FBFBFD is new to Plotly's color palette - I would use white instead, and invert the background on the thumb divs in these sections as whitesmoke:

![screen shot 2015-05-06 at 10 50 30 pm](https://cloud.githubusercontent.com/assets/1865834/7507661/2ea7d254-f441-11e4-92dc-292770888367.png)

- [ ] Needs a spaces around the "/". Let's also make the nav start at "Help" as its root, and the nav to help.plot.ly/tutorials/ 

![screen shot 2015-05-06 at 10 46 40 pm](https://cloud.githubusercontent.com/assets/1865834/7507663/3b587ae4-f441-11e4-9753-327f41cf07f9.png)

- [ ] Let's add navigational pills here:

![screen shot 2015-05-06 at 10 55 05 pm](https://cloud.githubusercontent.com/assets/1865834/7507700/d42db1c6-f441-11e4-9572-bd87f9b77c1c.png)

- [ ]  Plotly logo and help blurb could be closer together and centered:

![screen shot 2015-05-06 at 10 56 16 pm](https://cloud.githubusercontent.com/assets/1865834/7507711/fe92348c-f441-11e4-91f6-7020c8a2468b.png)

- [ ] Could change css classes to follow smaccs. I don't know much about this myself, but other front end folks seem to enjoy this methodology.

- [ ] Maybe change opacity on these guys on hover to entice clickgin - I watched a client today struggle on this page - https://plot.ly/learn/ - not knowing he could click on the images:

![image](https://cloud.githubusercontent.com/assets/1865834/7507763/c40c28e4-f442-11e4-8459-1da1df0628fe.png)

- [ ] Let's add these contextual snippets to the top thumbs at help.plot.ly, but make them appear on hover (same as how the 3 API client thumbs work):

![image](https://cloud.githubusercontent.com/assets/1865834/7507834/259ea806-f444-11e4-8ae9-57d05d2b8836.png)

**Comment by chriddyp** [comment]
Some stuff for SEO:

- [ ] A few more meta tags. This is what we use on Plotly's main side, we can use the same thing here: 
  ```
<!-- SEO Tags - title, meta_description, image -->
<title>{% if tags and tags.title %}{{tags.title}}{% else %}plotly{% endif %}</title>
<meta name="description" content="{% if tags and tags.meta_description %}{{tags.meta_description}}{% else %}Plotly is the easiest way to graph and share your data.{% endif %}">

<!-- Bing tags -->
<meta name="msvalidate.01" content="D319859A832F9F1D15A7646E2A42150A" />
<!-- /Bing tags -->

<!-- Facebook tags -->
<meta property="og:title" content="{% if tags and tags.title %}{{tags.title}}{% else %}plotly{% endif %}"/>
<meta property="og:type" content="website"/>
<meta property="og:image" content="{% if tags and tags.image %}{{tags.image}}{% else %}{% static 'img/tinkerbell_thumbnail_2.png' %}{% endif %}">
<meta property="og:description" content="{% if tags and tags.meta_description %}{{tags.meta_description}}{% else %}Plotly is the easiest way to graph and share your data.{% endif %}"/>
<meta property="og:url"
<meta property="fb:admins" content="1123751525"/>
<meta property="fb:admins" content="22418"/>
<!--/ Facebook tags -->

<!-- twitter tags -->
<meta name="twitter:card" content="photo" />
<meta name="twitter:title" content="{% if tags and tags.title %}{{tags.title}}{% else %}plotly{% endif %}"/>
<meta name="twitter:url" content="{% if tags and tags.url %}{{tags.url}}{% endif %}"/>
<meta name="twitter:description" content="{% if tags and tags.meta_description %}{{tags.meta_description}}{% else %}Plotly is the easiest way to graph and share your data.{% endif %}"/>
<meta name="twitter:image" content="{% if tags and tags.image %}{{tags.image}}{% else %}{% static '<<SOME IMAGE LINK HERE>>' %}{% endif %}"/>
<meta name="twitter:site" content="@plotlygraphs"/>
<!--/ twitter tags -->

<!-- Favicon -->
<link rel="shortcut icon" href="{{ PLOTLY_FAVICON_URL }}" />
<!--/ Favicon -->
   ```
  
   These tags are what define how links appear in Facebook and Twitter (e.g https://twitter.com/rossgoodwin/status/596375927782842370)

- [ ] Fill in the "twitter:image" tag with a nice default image, like http://i.imgur.com/nw806BP.png

**Comment by NicoleGrondin** [comment]
Hi @jackparmer 
Just nailing down the final bugs with help.plot.ly :)  
I thought I would take you up on your offer and pose you a css riddle:

The embed graphs keep squishing on the tutorial pages. e.g.: 
http://help.plot.ly/how-to-make-a-box-plot-online/

By disabling the script, styling works easily. But if the script is active, changes to the <div><a> or <img> don't seem to work.

Thoughts?

**Comment by NicoleGrondin** [comment]
** divs, images or links **

**Comment by jackparmer** [comment]
Hm, yeah, that's a weird one. Hey @andrefarzat , is there a way to increase the height on the embed here, or do we have to use the <iframe> syntax?
http://help.plot.ly/how-to-make-a-box-plot-online/

Markdown is here:
https://github.com/plotly/plotly.github.io/blob/master/_posts/2015-04-23-how-to-make-a-boxplot.md

**Comment by andrefarzat** [comment]
@jackparmer as we discussed, maybe increasing the width of the wrapper would help fix the height. The iframe syntax would work, but we lose the resize feature ( which might not be a problem, for the layout isn't responsive )

**Comment by andrefarzat** [comment]
* Oops, the layout is responsive ... so it's better using the script :smile_cat:

**Comment by NicoleGrondin** [comment]
@andrefarzat Thanks! I was stumped on this one :+1:
