### ISSUE TITLE
missing 3d scatter thumbnail

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.github.io#441]
![screen shot 2018-11-27 at 1 43 06 pm](https://user-images.githubusercontent.com/2789078/49103822-62916e80-f24a-11e8-89d4-fa3918db6761.png)

**Comment by nicolaskruchten** [comment]
This was fixed by changing the case on the thumnail filename from `3d` to `3D` so it wasn't related to the merge overwrite after all.

I still don't know why/how the merge-overwrite happened.
