### ISSUE TITLE
Replace "Getting Data" with a dash app

### ISSUE THREAD

**Issue by tarzzz** [plotly/plotly.github.io#490]
Replace [Getting Data](https://help.plot.ly/getting-data/) page with a page that illustrates how to build a Dash App on top of data from an open data portal like data.gov.

Required for: https://github.com/plotly/streambed/issues/12491#issue-410922540

**Comment by cldougl** [comment]
create app in: https://github.com/plotly/simple-example-chart-apps then add redirect to redirect from https://help.plot.ly/getting-data/ to the dash app

**Comment by michaelbabyn** [comment]
I think it makes sense to put this in an iframe so that we can add some context about what the app is and why the user was redirected to to it in the case that they were trying to use the `/external` endpoint. @cldougl , what do you think?

**Comment by cldougl** [comment]
+1 that would be great @michaelbabyn 
may want to add link to app and link to code in the context paragraph as well so users can open standalone if they wish
