### ISSUE TITLE
embed tutorial doesn't explain wordpress.com

### ISSUE THREAD

**Issue by mariahhamel** [plotly/plotly.github.io#51]
@chriddyp: just to confirm I haven't missed an update--it's possible to embed plotly graphs via plugin for wordpress.org, but not wordpress.com. The only solution on wordpress.com is to embed a static image and then link to the plotly graph. 

looks like an update of our tutorial deleted that part.

**Comment by scjody** [comment]
Note that there's a thing called oEmbed that may allow wordpress.com to embed plots like with the plugin.  I came across it during the Wordpress plugin debugging I did on Friday and I don't know how it works but it looks useful.

If you want someone to investigate, please log another issue.  I don't know who's best to do this though.

**Comment by cldougl** [comment]
http://help.plot.ly/embed-graphs-in-websites/#step-10-embed-on-wordpress
