### ISSUE TITLE
Prep landing pages for Falcon and Spectacle Editor

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.github.io#522]
We want to redirect:
* https://plot.ly/online-presentation-tool/ to  https://help.plot.ly/slide-decks/
* https://plot.ly/free-sql-client-download to https://help.plot.ly/database-connectors/personal-login/

so we need to prep for that traffic

**Comment by jdamiba** [comment]
This will involve:
- [x] editing https://help.plot.ly/slide-decks/ to include download links
- [x] editing https://help.plot.ly/database-connectors/personal-login/ to include download links
- [x] editing how-to-enter-data.md with internal link to falcon
