### ISSUE TITLE
Quotes on iframe embed don't copy/paste correctly

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.github.io#53]
Here:

http://help.plot.ly/embed-graphs-in-websites/

<iframe
width=”640″
height=”480″
frameborder=”0″
seamless=”seamless”
scrolling=”no”
src=”https://plot.ly/~Dreamshot/411/.embed?width=640&height=480″
></iframe>

**Comment by msund** [comment]
Quotes were labelled differently. Should be fixed now with https://github.com/plotly/plotly.github.io/commit/d3522c179779fc609448228dabc0e8a82ee8ed72.
