### ISSUE TITLE
tutorial on how to update the data behind a plot

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.github.io#57]
we get so many questions about this, this needs to be a tutorial so we stop writing incomplete help responses to users.
now that every plot has an associated grid, it's possible to edit the data behind *every* plot made

to clarify, tutorial should include:
- how to find the grid that is related to your plot (does "view data" work?)
- how you need to close and reopen the plot to see changes
- how to add a new trace to a plot by opening several files from /organize and using "insert into"

**Comment by cldougl** [comment]
http://help.plot.ly/update-a-graphs-data/
