### ISSUE TITLE
hover mode explanation

### ISSUE THREAD

**Issue by mariahhamel** [plotly/plotly.github.io#58]
Section 4 of [this tutorial](http://help.plot.ly/zoom-pan-hover-controls/) is called Change the Hover Mode. I think it would be useful to add some screen shots to show that we can show closest point on hover, or compare data on hover. I didn't see this in the gif.

<img width="606" alt="screen shot 2015-07-28 at 1 54 34 pm" src="https://cloud.githubusercontent.com/assets/5942601/9008273/18d350d4-3767-11e5-8bfe-6f8c43f71b2c.png">
<img width="616" alt="screen shot 2015-07-28 at 1 54 21 pm" src="https://cloud.githubusercontent.com/assets/5942601/9008278/1c5ea3ac-3767-11e5-8152-10fd16801172.png">

A couple images showing the difference on the graph would be nice too.

@MatthewHiscock Do you have time for this one?

**Comment by mariahhamel** [comment]
Actually, a tutorial explaining what each of those buttons in the upper right of every graph would be useful too.

**Comment by MatthewHiscock** [comment]
@mariahhamel I can give it a shot

**Comment by MatthewHiscock** [comment]
@mariahhamel - just so I'm clear, you mean to add that on the "Zoom, Pan, and Hover Controls in Plotly Graphs" tutorial, or on the linked "Dates, Time Series and Timestamp Format in Plotly" tutorial?

**Comment by etpinard** [comment]
FYI parts of the functionality will change in https://github.com/plotly/streambed/pull/3291

**Comment by MatthewHiscock** [comment]
@etpinard can I assume things are settled now and it's safe to proceed? Or are there more changes forthcoming?
