### ISSUE TITLE
explain how sharing works

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.github.io#61]
- what's a secret link? how does that work?
- how do shared folders work? 
- how does this work with the API?

plotly is packed with rich sharing features - it'd be great to have a tutorial that was discoverable via google

@MatthewHiscock - if you have a few free cycles, do you want to work on this one next?

**Comment by MatthewHiscock** [comment]
@chriddyp - sure, I'll slot it in.

**Comment by MatthewHiscock** [comment]
@chriddyp - is there anywhere specific I should go to for this info? In some cases it's obvious, but I want to make sure I don't miss anything, especially for the API stuff, which I'm not as knowledgeable about.

**Comment by chriddyp** [comment]
@MatthewHiscock you'll probably just need to ask one of us. @alexander-daniel thankfully cleaned up a lot of the sharing issues around folders, so the help messages inside "organize" around folders and sharing should be clear enough for you to understand. and if its not, then we should change it so that it is! around privacy and sharing in the APIs, @aneda can help you, she just updated how sharing works in the python api and can point you in the right direction for the other libraries.
i'd also model the tutorial around how google drive and dropbox explain sharing in their tutorials - their messaging is usually super clear!

**Comment by cldougl** [comment]
http://help.plot.ly/how-sharing-works-in-plotly/
