### ISSUE TITLE
ReferenceError when loading Plotly on a page with Requirejs

### ISSUE THREAD

**Issue by trgn** [plotly/plotly.github.io#74]
(not even sure this belongs here. does it?)

Anyways, here goes:

`Plotly` (`plotly_20150812a_basic/plotly.min.js`) throws a `ReferenceError` when it shares a page with `requirejs`. This happens when (1) either loading `Plotly`  as a shim, or when (2) importing it with a `<script>` tag after `requirejs` is already loaded.

The issue I believe is the last statement, probably tagged on by the release process.

    Plotly.BUILD = "20150812a_basic"

The `Plotly` global does not exist yet, because, when it detects the presence of `define`, the factory function to create `[window|module].Plotly` has not yet executed. 

As an aside, If `Plotly` is supposed to be AMD-compatible, I am not even sure it should create a global to begin with. Also, since AMD loaders have sufficient support to load non-AMD scripts, so I am not even sure if `Plotly` should be checking for the presence of `define` to bootstrap differently.

**Comment by etpinard** [comment]
@trgn 

> (not even sure this belongs here. does it?)

The best option right now for questions on plotlyjs is http://stackoverflow.com/questions/tagged/plotly .

> `plotly.min.js` throws a ReferenceError when it shares a page with `requirejs`.

Correct. `plotly.min.js` is incompatible with `requirejs`. `plotly.min.js` is [browserify](https://github.com/substack/node-browserify) bundle which makes use of the `require` function from `CommonJs`. More info on their differences [here](http://stackoverflow.com/a/16522990/4068492).

>  If `plotly.min.js` is supposed to be AMD-compatible, I am not even sure it should create a global to begin with. 

`plotly.min.js` creates one global: `Plotly`.


I'm closing this issue as this repo is meant for documentation purposes only, but feel free to ask any other questions regarding plotly on stackoverflow or to me personally via email.
