### ISSUE TITLE
Tutorials that need updating

### ISSUE THREAD

**Issue by mariahhamel** [plotly/plotly.github.io#8]
The following tutorials need to be updated.
- [x] [HTML](http://help.plot.ly/adding-HTML-and-links-to-charts/)
  - [x] missing images
  - [x] HTML code needs to be fixed for viewing
    (https://cloud.githubusercontent.com/assets/5942601/7536346/108a2584-f55d-11e4-82b0-510772f48d9e.png)
- [x] [Getting data](http://help.plot.ly/getting-data/)
  - [x] Add import.io
  - [x] Add webplotdigitizer
  - [x] Add Chris' [external sync](http://chriddyp.github.io/external-source-plotter/) Perhaps a separate tutorial for this? 
- [x] [Line of best fit](http://help.plot.ly/create-a-line-of-best-fit-online/)
  - [x] Missing image (your graph should look something like this:)
- [x] [Adding data to the grid](http://help.plot.ly/add-data-to-the-plotly-grid/)
  - [x] Missing image (your graph should look something like this:)
- [ ] Text styling (see Alex's comment below)
- [ ] Area graph photos need to be redone. TRACES box is still Style box.

**Comment by mariahhamel** [comment]
@NicoleGrondin I'm guessing you will notice things that need updating as you go. Let's keep the required tutorial updates here, so I don't forget about anything.

**Comment by NicoleGrondin** [comment]
@mariahhamel Sounds good! I'll add tutorials as I see them.

**Comment by alexcjohnson** [comment]
- [ ] [text styling](http://help.plot.ly/adding-HTML-and-links-to-charts/): add new free-css options, see my response to missbaza:

```
Underlining:

Here is some <span style="text-decoration:underline">underlined text</span>

Color is a little weird because it's SVG and not regular HTML, so you need fill instead of color:

The default is black, but <span style="fill:#ff0000">this is red</span>

There are a lot of ways you can specify colors in css, Plotly will accept them all: http://www.w3schools.com/cssref/css_colors_legal.asp
```
Any other style attributes people would want to use? Also may want to mention that you can use multiple at once with semicolons (`<span style="fill:red;text-decoration:line-through">deleted text</span>`) and you can style any tag, not just span (`<b style="fill:green">Green giant!</b>`)

**Comment by mariahhamel** [comment]
+1, thanks @alexcjohnson
