### ISSUE TITLE
Tutorials to add

### ISSUE THREAD

**Issue by mariahhamel** [plotly/plotly.github.io#9]
**General tutorials**
- [ ] Forecasting (claim here)
- [ ] Subplots 
- [x] Exponential fits (Mariah)
- [x] Quadratic fits
- [x] 4th degree polynomial fits (Mariah)
- [ ] Custom fit functions (claim here)
- [ ] Advanced 3d options (aspect ratio, camera save, etc)
- [x] "How to color the points of a scatter plot by a third column" (Ben Noll)
- [x] "How to label points with text in a scatter plot" (Ben Noll)
- [x] Zoom, pan, and hover controls in Plotly graphs (Ben Noll)
- [ ] Combination plots (see the end of this [blog post](http://blog.plot.ly/post/118355223592/how-to-analyze-data-eight-useful-ways-you-can))
- [ ] 3d surface plots
- [ ] semi-log and log plots
- [ ] d3 numeric ticks (see issue [here](https://github.com/plotly/streambed/pull/2457#issuecomment-106538616)) to allow number formatting like commas. 

**Data literacy tutorials**
- [ ] Statistics 
  - [ ] What is hypothesis testing (Corinne)
  - [ ] ANOVA (Corinne)
  - [ ] Chi-square (Corinne)
  - [ ] T-test (Corinne)
  - [ ] What is a quantile plot
- [ ] semi-log and log plots
- [ ] Graphing best practices (basically turn [this](http://chriddyp.github.io/elements-of-style/rough-draft/) into a tutorial, or series of tutorials)
- [ ] parametric surfaces [see here](http://www.mathworks.com/help/matlab/visualize/representing-a-matrix-as-a-surface.html#f0-15933)
- [ ] cartesian and polar coordinates

**Comment by mariahhamel** [comment]
@jackparmer @chriddyp @msund @mkcor  Here's a spot for our tutorial wish list. These are for the help.plot.ly page, likely with some overlap for education.

Please add as you have ideas.

**Comment by jackparmer** [comment]
Ben N. (@Dreamsh0t) is adding these!
- [ ] "How to color the points of a scatter plot by a third column"
- [ ] "How to label points with text in a scatter plot"
- [ ] Zoom, pan, and hover controls in Plotly graphs

**Comment by msund** [comment]
Nice. Bring on the tutorials! Two that I daydream about:

- [ ] "How to choose a statistical test"
- [ ] "How to choose a graph", which could use the content from [this post](http://blog.plot.ly/post/118355223592/how-to-analyze-data-eight-useful-ways-you-can).

**Comment by mariahhamel** [comment]
@msund want to ask dana to do the "how to choose a graph" from her post?

The "How to choose a statistical test" will be in Corinne's "What is hypothesis testing". We can rename, of course.

**Comment by msund** [comment]
@Dreamsh0t knows our Tumblr -> WP translation best. Ben, would you mind translating the [post](http://blog.plot.ly/post/118355223592/how-to-analyze-data-eight-useful-ways-you-can) into a help page tutorial?

**Comment by chriddyp** [comment]
- [ ] Importing images by URL into Word and Powerpoint, i.e. syncing your Plotly graphs to your documents and presentations with "INCLUDEPICTURE"

**Comment by chriddyp** [comment]
- [ ] Importing images by URL into LaTeX documents with wget and curl, i.e. syncing your Plotly graphs to your LaTeX papers and slides
